# These are supported funding model platforms

github: [rutvij26]
# patreon: your-patreon-username
# open_collective: your-open-collective-username
# ko_fi: your-ko-fi-username
# tidelift: your-tidelift-username
# community_bridge: your-community-bridge-username
# liberapay: your-liberapay-username
# issuehunt: your-issuehunt-username
# otechie: your-otechie-username
# custom: ["https://your-custom-funding-url.com"]

# If you want to display a custom message, add it here:
message: "If you find this chess engine project valuable, consider supporting its development! 🎮🧠"
